tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "sass/sass"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Modern replacement for 'ls'
brew "exa"
# Command-line tool to interact with exercism.io
brew "exercism"
# Collection of GNU find, xargs, and locate
brew "findutils"
# Distributed revision control system
brew "git"
# GNU implementation of which utility
brew "gnu-which"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Pager program similar to more
brew "less"
# Mac App Store command-line interface
brew "mas"
# Free (GNU) replacement for the Pico text editor
brew "nano"
# Parser generator tool and incremental parsing library
brew "tree-sitter"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Cross-shell prompt for astronauts
brew "starship"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Command-line interface for Vercel
brew "vercel-cli"
# JavaScript package manager
brew "yarn"
# UNIX shell (command interpreter)
brew "zsh"
# Real-time type-ahead completion for Zsh
brew "zsh-autocomplete"
# Stylesheet Preprocessor
brew "sass/sass/sass"
# Command-line helper for the 1Password password manager
cask "1password-cli", args: { no_quarantine: true }
# Application launcher and productivity software
cask "alfred", args: { no_quarantine: true }
# Enable Windows-like alt-tab
cask "alt-tab", args: { no_quarantine: true }
# Multi-track audio editor and recorder
cask "audacity", args: { no_quarantine: true }
# Menu bar icon organizer
cask "bartender", args: { no_quarantine: true }
# Tool to remove unnecessary files and folders from disk
cask "cleanmymac", args: { no_quarantine: true }
# Utilities designed to make common development tasks easier
cask "devtoys", args: { no_quarantine: true }
# Voice and text chat software
cask "discord", args: { no_quarantine: true }
# Reimagine your terminal
cask "fig", args: { no_quarantine: true }
# Web browser
cask "firefox", args: { no_quarantine: true }
# Developer targeted fonts with a high number of glyphs
cask "font-fira-code-nerd-font", args: { no_quarantine: true }
# Developer targeted fonts with a high number of glyphs
cask "font-fira-mono-nerd-font", args: { no_quarantine: true }
# Developer targeted fonts with a high number of glyphs
cask "font-hack-nerd-font", args: { no_quarantine: true }
# Disk space cleaner that finds and deletes duplicated and similar files
cask "gemini", args: { no_quarantine: true }
# Git client focusing on productivity
cask "gitkraken", args: { no_quarantine: true }
# Terminal built on web technologies
cask "hyper", args: { no_quarantine: true }
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2", args: { no_quarantine: true }
# Minimal browser that protects privacy
cask "min", args: { no_quarantine: true }
# Calculator and converter application
cask "numi", args: { no_quarantine: true }
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian", args: { no_quarantine: true }
# All system and utility switches in one place
cask "one-switch", args: { no_quarantine: true }
# Collaboration platform for API development
cask "postman", args: { no_quarantine: true }
# All-in-one bookmark manager
cask "raindropio", args: { no_quarantine: true }
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle", args: { no_quarantine: true }
# Music streaming service
cask "spotify", args: { no_quarantine: true }
# Open-source code editor
cask "visual-studio-code", args: { no_quarantine: true }
# Mind mapping and brainstorming tool
cask "xmind", args: { no_quarantine: true }
# Video communication and virtual meeting platform
cask "zoom", args: { no_quarantine: true }
mas "1Password for Safari", id: 1569813296
mas "Day One", id: 1055511498
mas "GarageBand", id: 682658836
mas "GoodNotes", id: 1444383602
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Save to Raindrop.io", id: 1549370672
mas "Speedtest", id: 1153157709
mas "Things", id: 904280696
mas "Twitter", id: 1482454543
mas "Ultra Character Map", id: 520265986
mas "Yubico Authenticator", id: 1497506650
