import = [
    "~/.config/alacritty/themes/dracula-pro-van-helsing.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
dimensions = { columns = 110 , lines = 30 }
padding.x = 15
padding.y = 15

decorations = "Buttonless"

opacity = 0.9
blur = false

option_as_alt = "Both"

[cursor]
blink_interval = 750

[cursor.style]
shape = "Beam"
blinking = "Always"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16
