  # Check for the existence of the passed-in command but discard the outcome
  # through redirection whether successful or erroneous because our
  # script will use the exit code.
function exists() {
  # `command -v` is similar to `which`
  # $1 is the first command passed into the exists function
  # https://stackoverflow.com/a/677212/1341838
  command -v $1 >/dev/null 2>&1
}