export ZSH="/Users/wix/.oh-my-zsh"

ZSH_THEME="dracula"
CASE_SENSITIVE="true"
ENABLE_CORRECTION="true"

plugins=(git brew bun)

source $ZSH/oh-my-zsh.sh

export EDITOR='nano'

# -------
# Aliases
# -------

alias ls='exa -laFh --git --icons --color=always'
alias exa='exa -laFh --git --icons --color=always'
alias xl='exa -lag --icons --color=always' 
alias bbd="~/.dotfiles/brew/generate_brewfile.zsh"
alias trail='<<<${(F)path}'
alias cm="npx cz"

# -----------
# Variables
# -----------

export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export HOMEBREW_CASK_OPTS="--no-quarantine"
export NVM_DIR="$HOME/.nvm"
NULLCMD=bat
skip_global_compinit=1

# Exa Colors
[[ -f ~/.dotfiles/zsh/exa/exa_colors.zshrc ]] && source ~/.dotfiles/zsh/exa/exa_colors.zshrc

# Load NVM
export NVM_DIR="$HOME/.nvm"
    [ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" # This loads nvm
    [ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion

# Add Locations to $PATH Variable
# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export PATH="/opt/homebrew/opt/curl/bin:$PATH"

# Zoxide
eval "$(zoxide init zsh)"