[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"

[nodejs]
symbol = "[⬢](bold green) "
disabled = true

[git_status]
disabled = true

[line_break]
disabled = true